# Base64 encode the values stored in a Kubernetes Secret
# pbpaste | base64 | pbcopy
# pbpaste | base64 --decode
apiVersion: v1
kind: Secret
metadata:
  name: dunamis-env-secrets
type: Opaque
data:
  SECRET: eW91cnNlY3JldA==